version: "3"
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: on-failure
    build: . # build from current directory's Dockerfile
    ports: 
      - "4001:8081" # <port_on_local_machine:port_on_container>


    